---

- hosts: all
  become: true
  tasks:

  - name: update and upgrade the servers
    apt: 
      update_cache: yes
      upgrade: yes

  - name: set timezone to Africa/Lagos
    tags: time
    become: true
    command: timedatectl set-timezone Africa/Lagos

  - name: install apache2
    tags: apache
    apt:
      name:
        - apache2
      state: latest

  - name: remove index.html
    file:
      path: /var/www/html/index.html
      state: absent

  - name: use the printf script
    shell: |
      sudo echo "<h1>Hello ,this is my hostname:</h1>" >> /var/www/html/index.html
      sudo echo "<p>Hostname: $(hostname -f)</p>" >> /var/www/html/index.html
      sudo echo "<h1>This is my IP address that changes whenever the web page is refreshed:</h1>" >> /var/www/html/index.html
      sudo echo "<p>$(hostname -I)</p>" >> /var/www/html/index.html
      sudo echo "<h1> My OS:</h1>" >> /var/www/html/index.html
      sudo echo "<p>Operating System: $(hostnamectl | grep 'Operating System' | cut -d ' ' -f5-)</p>" >> /var/www/html/index.html
      sudo echo "<h1>This is my Timezone:</h1>" >> /var/www/html/index.html
      sudo echo "<p>Timezone: $(timedatectl | grep 'Time zone' | awk '{print $3}')</p>" >> /var/www/html/index.html
      sudo echo "<h1>Current Date and Time:</h1>" >> /var/www/html/index.html
      sudo echo "<p id='liveTime'></p>" >> /var/www/html/index.html
      sudo echo "<script>setInterval(function() { document.getElementById('liveTime').innerHTML = 'Current Date and Time: ' + new Date().toLocaleString(); }, 1000);</script>" >> /var/www/html/index.html
      
    notify: restart Apache
  

  handlers:
    - name: restart Apache
      tags: restart
      service:
        name: apache2
        state: restarted